"use strict";

var TYPE_USER = 'user';
var TYPE_CONTRACT = 'contract';
var TYPE_BUILTIN = 'builtin';
var TYPE_NULL = 'null';
var PREFIX_CFX = 'cfx';
var PREFIX_CFXTEST = 'cfxtest';
var PREFIX_NET = 'net';
var NETID_MAIN = 1029;
var NETID_TEST = 1;
module.exports = {
  TYPE_USER: TYPE_USER,
  TYPE_CONTRACT: TYPE_CONTRACT,
  TYPE_BUILTIN: TYPE_BUILTIN,
  TYPE_NULL: TYPE_NULL,
  PREFIX_CFX: PREFIX_CFX,
  PREFIX_CFXTEST: PREFIX_CFXTEST,
  PREFIX_NET: PREFIX_NET,
  NETID_MAIN: NETID_MAIN,
  NETID_TEST: NETID_TEST
};